spring.application.name=AdminSpring

# ServerPort
server.port=8080

# Firebase
firebase.database.url=https://quizapp-e6abb-default-rtdb.firebaseio.com
firebase.service.account=src/main/resources/quizapp-e6abb-firebase-adminsdk-6ka9w-6304b1128d.json

# Cloudinary
cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET

# Disable JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
