spring.application.name=AdminSpring
spring.datasource.url=jdbc:postgresql://localhost:5432/CoffeeShopp
spring.datasource.username=postgres
spring.datasource.password=4252
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect